name: MoringaPair CI/CD

on:
  push:
    branches: [ main, development]
  pull_request:
    branches: [ main, development ]

jobs:
  react:
    name: React
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Build
        run: |
          cd client
          npm run build
      - name: Test
        run: |
          cd client
          npm run test
  rails:
    name: Ruby on Rails
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd api
          bundle install
  #     - run: cd api && bundle exec rails db:migrate RAILS_ENV=test
  #     - run: cd api && bundle exec rspec spec